name: Auto Build & Push OpenMemory Docker Image

on:
  push:
    branches:
      - main  # 监听 main 分支的更新
  schedule:
    - cron: '0 3 * * *'  # 每天 UTC 时间 3:00 自动运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Repository Files
        run: ls -la openmemory/

      - name: Set up Python & Poetry
        run: |
          sudo apt update
          sudo apt install python3-pip
          curl -sSL https://install.python-poetry.org | python3
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry --version

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build API & UI Docker Images
        working-directory: openmemory
        run: |
          make build  # 构建 MCP 服务器和 UI
        
      - name: Push Separate API & UI Images
        run: |
          docker tag openmemory-mcp:latest ${{ secrets.DOCKER_USERNAME }}/openmemory-mcp:latest
          docker tag openmemory-ui:latest ${{ secrets.DOCKER_USERNAME }}/openmemory-ui:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/openmemory-mcp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/openmemory-ui:latest


