name: Auto Build & Push OpenMemory Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Environment Files
        run: make -C openmemory env  # 确保 .env 文件正确复制

      - name: Verify .env File Exists
        run: |
          ls -la openmemory/api/
          cat openmemory/api/.env

      - name: Run Makefile Build (Docker Compose)
        run: make -C openmemory build  # 使用 make 构建

      - name: Start Containers
        run: make -C openmemory up  # 运行 docker compose up

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./openmemory
          file: ./openmemory/Dockerfile
          push: true
          tags: mem0ai/openmemory:latest
