name: Auto Build & Push OpenMemory Docker Image

on:
  push:
    branches:
      - main  # 监听 main 分支的更新
  schedule:
    - cron: '0 3 * * *'  # 每天 UTC 时间 3:00 自动运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Repository Files
        run: ls -la openmemory/

      - name: Set up Python & Poetry
        run: |
          sudo apt update
          sudo apt install python3-pip
          curl -sSL https://install.python-poetry.org | python3
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry --version

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Environment Files
        working-directory: openmemory
        run: make env  # 复制 .env.example 到 .env

      - name: Verify .env File Exists
        run: |
          ls -la openmemory/api/
          cat openmemory/api/.env || echo "⚠️ .env 文件未正确创建！"

      - name: Build API & UI Docker Images
        working-directory: openmemory
        run: make build  # 构建 MCP 服务器和 UI
        

      - name: Build Combined OpenMemory Image
        working-directory: openmemory
        run: docker build -t mem0ai/openmemory:latest -f Dockerfile .

      - name: Push Separate API & UI Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/openmemory-mcp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/openmemory-ui:latest

      - name: Push Combined OpenMemory Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/openmemory:latest

